### ISSUE TITLE
Ability to Change CODIUS_XRP_PER_MONTH dynamically

### ISSUE THREAD

**Issue by soliddash** [codius/codiusd#42] opened 2018-06-12 12:21 UTC
I think this config entry MUST be dynamically changeable at some point since this is the only adjustment granting competitiveness and profitability. Standard HUP? reading from config file?

**Comment by adrianhopebailie** [comment] 2018-06-14 09:29
@andywong418 I'm not sure this is resolved by 59386d5.

My interpretation of the issue is that @soliddash wants a way to tie the new `getCurrencyPerSecond()` function to a rates backend so the value is not hardcoded into the config.

Have left closed but feel free to re-open @soliddash if this is the case.

Also, please try and provide some more details on the requirement as this will help a lot with designing a solution.

**Comment by soliddash** [comment] 2018-06-14 09:51
I wanted to be able to change this somewhere in a config file and send stand HUP kill process to rehash it... Unless this new method lets you change it with a curl POST?

**Comment by spearl** [comment] 2018-06-20 00:53
I think this is still a valid feature request that we can think about designing as we go forward. Different rates will be an inherent part of the system so being able to change the rate you charge without having to shutdown (and kill all of your guests) would be very advantageous. So I'm going to reopen to keep this on the radar.

**Comment by spearl** [comment] 2018-06-26 17:49
This feature can be added as a POST to the admin API

**Closed** 2018-07-12 16:23 UTC
Labels: feature request
